# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'DWT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DWT

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'
  # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga/Yoga.podspec"

    pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/'
    pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
    pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
    pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
    pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
    
   ###################
   pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"

   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
   pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
   pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
   ###################

    pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
    pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
    pod 'react-native-maps', path: rn_maps_path
    pod 'GoogleSignIn'
#    pod 'XCDYouTubeKit', '~> 2.5'
    # Stripe
#    pod 'Stripe', '~> 14.0.0'
    # Install additional dependencies
    pod 'Firebase/Core'
#    pod 'Firebase/Auth'
#    pod 'Firebase/Crash'
#    pod 'Firebase/Database'
#    pod 'Firebase/Firestore'
    pod 'Firebase/Messaging'
#    pod 'Firebase/Performance'
#    pod 'Firebase/Storage'
    # Admobe
    pod 'Google-Mobile-Ads-SDK'
    # Facebook FBSDK
    pod 'FBAudienceNetwork', '~> 5.1.0' #facebook ads
    pod 'FacebookSDK'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    #Google Maps pods
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: rn_maps_path  # Unomment this line if you want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
    pod 'GooglePlaces'
    pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS

    pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
    
#    pod 'RNPaypal', :path => '../node_modules/react-native-paypal-lib/ios'

    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'




#    pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

    pod 'RNIap', :path => '../node_modules/react-native-iap'

    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

    pod 'react-native-admob', :path => '../node_modules/react-native-admob'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'





    pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'
    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'

    pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    pod 'lottie-ios', :path => '../node_modules/lottie-ios'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    pod 'Firebase/Auth'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

    pod 'react-native-apple-authentication', :path => '../node_modules/react-native-apple-authentication'
    # use_native_modules!

    pod 'RNPureJwt', :path => '../node_modules/react-native-pure-jwt'

  end

  # very important to have, unless you removed React dependencies for Libraries
  # and you rely on Cocoapods to manage it
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
